FROM library/ruby:2.4.2

RUN gem install bundler

RUN mkdir /app
RUN mkdir /template

ARG RAILS_VERSION=5.1.4
ENV RAILS_VERSION ${RAILS_VERSION}

COPY Gemfile /template/Gemfile
COPY rails-new.sh /usr/local/bin/rails-new
COPY rails-up.sh /usr/local/bin/rails-up

RUN chmod +x /usr/local/bin/rails*

RUN sed -i -- "s/RAILS_VERSION/${RAILS_VERSION}/g" /template/Gemfile

ARG INSTALL_RAILS=false
ENV INSTALL_RAILS ${INSTALL_RAILS}

RUN if [ ${INSTALL_RAILS} = true ]; then \
  apt-get update -qq --fix-missing \
  && apt-get install -y libqt4-dev \
  && gem install rails -v ${RAILS_VERSION} \
;fi

ARG INSTALL_POSTGRES=false
ENV INSTALL_POSTGRES ${INSTALL_POSTGRES}

RUN if [ ${INSTALL_POSTGRES} = true ]; then \
  apt-get update -qq --fix-missing \
  && apt-get install -y postgresql postgresql-contrib libpq-dev \
;fi

ARG INSTALL_NODE=false
ENV INSTALL_NODE ${INSTALL_NODE}

RUN if [ ${INSTALL_NODE} = true ]; then \
  apt-get update -qq --fix-missing \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh \
  && ./nodesource_setup.sh \
  && apt-get install -y nodejs build-essential \
;fi

# Set default work directory
WORKDIR /app
