FROM library/ruby:2.4.2

RUN gem install bundler

ARG INSTALL_RAILS=false
ARG RAILS_VERSION=5.1.4
ENV INSTALL_RAILS ${INSTALL_RAILS}
ENV RAILS_VERSION ${RAILS_VERSION}

RUN if [ ${INSTALL_RAILS} = true ]; then \
  gem install rails -v ${RAILS_VERSION} \
;fi

ARG INSTALL_NODE=false
ENV INSTALL_NODE ${INSTALL_NODE}

RUN if [ ${INSTALL_NODE} = true ]; then \
  apt-get update \
  && apt-get install -y nodejs \
;fi

RUN mkdir /app
RUN mkdir -p /var/www/ruby/rails-app

# Set default work directory
WORKDIR /app

COPY Gemfile /var/www/ruby/rails-app/Gemfile
