FROM library/ruby:2.4.2

RUN gem install bundler

RUN mkdir /app
RUN mkdir /template

ARG RAILS_VERSION=5.1.4
ENV RAILS_VERSION ${RAILS_VERSION}

COPY template/ /template/
COPY bin/ /usr/local/bin/

RUN chmod +x -R /usr/local/bin

RUN sed -i -- "s/RAILS_VERSION/${RAILS_VERSION}/g" /template/Gemfile

ARG INSTALL_POSTGRES=false
ENV INSTALL_POSTGRES ${INSTALL_POSTGRES}

RUN if [ ${INSTALL_POSTGRES} = true ]; then \
  apt-get update -qq --fix-missing \
  && apt-get install -y postgresql postgresql-contrib libpq-dev \
  && sed -i -- "s/sqlite3/postgresql/g" /usr/local/bin/rails-new \
;fi

ARG INSTALL_NODE=false
ENV INSTALL_NODE ${INSTALL_NODE}

RUN if [ ${INSTALL_NODE} = true ]; then \
  apt-get update -qq --fix-missing \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh \
  && bash ./nodesource_setup.sh \
  && rm nodesource_setup.sh \
  && apt-get install -y nodejs build-essential \
;fi

ARG INSTALL_YARN=false
ENV INSTALL_YARN ${INSTALL_YARN}

RUN if [ ${INSTALL_YARN} = true ]; then \
    curl -o- -L https://yarnpkg.com/install.sh | bash \
    && echo "" >> ~/.bashrc \
    && echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> ~/.bashrc \
;fi

# Set default work directory
WORKDIR /app
