language: bash
sudo: required
dist: trusty
services:
  - docker

env:
  matrix:
    - MY_RUBY_VERSION=2.5.0 RUBY_RAILS_VERSION=5.2.3

# Installing a newer Docker version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker version

script: ./travis-build.sh

notifications:
  email: false

cache:
  directories:
    - ~/.dockery/data/bundle/2.4.2
