version: '3.3'

services:

### Applications Code Container #############################

  ruby:
    volumes:
      - ${APPLICATIONS_PATH}:/apps
      - ${DATA_PATH}/${RUBY_BUNDLE_DIR}/${MY_RUBY_VERSION}:/usr/local/bundle

### Volumes Setup #############################################

volumes:
  ruby:
    driver: "local"
